export const ROLES = {
  ADMIN_GLOBAL: 'ADMIN_GLOBAL',
  ADMIN_EMPRESA: 'ADMIN_EMPRESA',
  GERENTE_OPERATIVO: 'GERENTE_OPERATIVO',
  JEFE_PUNTO: 'JEFE_PUNTO',
  OPERADOR: 'OPERADOR',
  CONSULTA: 'CONSULTA'
}

export const PERMISSIONS = {
  // Inventario
  'inventario.ver': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO, ROLES.JEFE_PUNTO, ROLES.OPERADOR, ROLES.CONSULTA],
  'inventario.ajustar': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO, ROLES.JEFE_PUNTO],

  // Transferencias
  'transferencias.crear': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO],
  'transferencias.confirmar': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO, ROLES.JEFE_PUNTO, ROLES.OPERADOR],
  'transferencias.editar': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO],

  // Conteos
  'conteos.programar': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO],
  'conteos.ejecutar': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO, ROLES.JEFE_PUNTO, ROLES.OPERADOR],

  // Reportes
  'reportes.ver': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO, ROLES.JEFE_PUNTO, ROLES.CONSULTA],
  'reportes.exportar': [ROLES.ADMIN_GLOBAL, ROLES.ADMIN_EMPRESA, ROLES.GERENTE_OPERATIVO, ROLES.JEFE_PUNTO]
}
